# Generated by Django 5.2.4 on 2025-07-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(default=1, verbose_name='Описание услуги (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_pl',
            field=models.TextField(default=1, verbose_name='Описание услуги (PL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_ru',
            field=models.TextField(default=1, verbose_name='Описание услуги (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='description_ua',
            field=models.TextField(default=1, verbose_name='Описание услуги (UA)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(default=1, max_length=200, verbose_name='Название услуги (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name_pl',
            field=models.CharField(default=1, max_length=200, verbose_name='Название услуги (PL)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(default=1, max_length=200, verbose_name='Название услуги (RU)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name_ua',
            field=models.CharField(default=1, max_length=200, verbose_name='Название услуги (UA)'),
            preserve_default=False,
        ),
    ]
