# Generated by Django 5.2.4 on 2025-08-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_service_description_remove_service_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('photo', models.ImageField(upload_to='employees/', verbose_name='Фото')),
                ('position', models.CharField(max_length=150, verbose_name='Вакансия')),
                ('profession', models.CharField(max_length=150, verbose_name='Професия')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
                ('years_in_poland', models.PositiveIntegerField(verbose_name='Время перебывания в Польше')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pracownik',
                'verbose_name_plural': 'Pracownicy',
            },
        ),
    ]
