# Generated by Django 5.2.4 on 2025-08-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa_firmy', models.CharField(max_length=255, verbose_name='Nazwa firmy')),
                ('nip', models.CharField(max_length=10, verbose_name='NIP')),
                ('regon', models.CharField(blank=True, max_length=9, null=True, verbose_name='REGON')),
                ('miasto', models.CharField(max_length=100, verbose_name='Miasto')),
                ('adres', models.CharField(max_length=255, verbose_name='Adres')),
                ('telefon_administracja', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon administracja')),
                ('telefon_legalizacja', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefon legalizacja')),
                ('email', models.EmailField(max_length=254, verbose_name='Adres e-mail')),
                ('data_dodania', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
            ],
            options={
                'verbose_name': 'Firma',
                'verbose_name_plural': 'Firmy',
                'ordering': ['nazwa_firmy'],
            },
        ),
    ]
