# Generated by Django 5.2.4 on 2025-08-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва платформи')),
                ('url', models.URLField(verbose_name='Посилання')),
            ],
            options={
                'verbose_name': 'Соціальна мережа',
                'verbose_name_plural': 'Соціальні мережі',
                'ordering': ['name'],
            },
        ),
    ]
