# Generated by Django 5.2.4 on 2025-08-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_privacypolicysection_privacypolicysubsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_pl', models.CharField(max_length=200, verbose_name='Tytuł (PL)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Tytuł (EN)')),
                ('title_ru', models.CharField(max_length=200, verbose_name='Tytuł (RU)')),
                ('title_ua', models.CharField(max_length=200, verbose_name='Tytuł (UA)')),
                ('company_name', models.CharField(max_length=150, verbose_name='Firma')),
                ('location', models.CharField(max_length=150, verbose_name='Lokalizacja')),
                ('description_pl', models.TextField(verbose_name='Opis (PL)')),
                ('description_en', models.TextField(verbose_name='Opis (EN)')),
                ('description_ru', models.TextField(verbose_name='Opis (RU)')),
                ('description_ua', models.TextField(verbose_name='Opis (UA)')),
                ('requirements_pl', models.TextField(blank=True, verbose_name='Wymagania (PL)')),
                ('requirements_en', models.TextField(blank=True, verbose_name='Wymagania (EN)')),
                ('requirements_ru', models.TextField(blank=True, verbose_name='Wymagania (RU)')),
                ('requirements_ua', models.TextField(blank=True, verbose_name='Wymagania (UA)')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pensja od')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Pensja do')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Data dodania')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Oferta ważna do')),
                ('status', models.CharField(choices=[('draft', 'Szkic'), ('published', 'Opublikowana'), ('closed', 'Zamknięta')], default='draft', max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Oferta pracy',
                'verbose_name_plural': 'Oferty pracy',
                'ordering': ['-published_at'],
            },
        ),
    ]
