# Generated by Django 5.2.4 on 2025-08-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_joboffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
    ]
