# Generated by Django 5.2.4 on 2025-08-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_contactrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_pl', models.CharField(max_length=200, verbose_name='Nazwa klasy (PL)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Nazwa klasy (EN)')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Nazwa klasy (RU)')),
                ('name_ua', models.CharField(max_length=200, verbose_name='Nazwa klasy (UA)')),
                ('name_es', models.CharField(max_length=200, verbose_name='Nazwa klasy (ES)')),
                ('description_pl', models.TextField(blank=True, null=True, verbose_name='Opis klasy (PL)')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Opis klasy (EN)')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Opis klasy (RU)')),
                ('description_ua', models.TextField(blank=True, null=True, verbose_name='Opis klasy (UA)')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Opis klasy (ES)')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='description_es',
            field=models.TextField(default=1, verbose_name='Opis usługi (ES)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name_es',
            field=models.CharField(default=1, max_length=200, verbose_name='Nazwa usługi (ES)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='description_en',
            field=models.TextField(verbose_name='Opis usługi (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_pl',
            field=models.TextField(verbose_name='Opis usługi (PL)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ru',
            field=models.TextField(verbose_name='Opis usługi (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description_ua',
            field=models.TextField(verbose_name='Opis usługi (UA)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=200, verbose_name='Nazwa usługi (EN)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_pl',
            field=models.CharField(max_length=200, verbose_name='Nazwa usługi (PL)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=200, verbose_name='Nazwa usługi (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name_ua',
            field=models.CharField(max_length=200, verbose_name='Nazwa usługi (UA)'),
        ),
    ]
