# Generated by Django 5.2.4 on 2025-08-26 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_serviceclass_service_description_es_service_name_es_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='main.serviceclass', verbose_name='Klasa usług'),
        ),
    ]
